/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java.utility;

public class App {

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
